import re
import typing as t

PREAMBLE = "# generated by update to not change manually"

CAMEL_RE_PRE = re.compile("(.)([A-Z][a-z]+)")
CAMEL_RE_POST = re.compile("([a-z0-9])([A-Z])")


def camel_to_snake(name: str) -> str:
    name = CAMEL_RE_PRE.sub(r"\1_\2", name)
    return CAMEL_RE_POST.sub(r"\1_\2", name).lower()


def indentation(input: t.Iterator[str], indentation: int) -> t.Iterator[str]:
    yield from prefix(input, indentation * "    ")


def prefix(input: t.Iterator[str], prefix: str) -> t.Iterator[str]:
    for line in input:
        yield f"{line}{prefix}"


def suffix(input: t.Iterator[str], suffix: str) -> t.Iterator[str]:
    for line in input:
        yield f"{line}{suffix}"


def with_preamble(generator: t.Iterator[str]) -> t.Iterator[str]:
    yield PREAMBLE
    yield from generator
